from mi_grafo import Grafo

grafo = Grafo(dirigido=False)

grafo.insertar_vertice('Luke Skywalker')
grafo.insertar_vertice('Darth Vader')
grafo.insertar_vertice('Yoda')
grafo.insertar_vertice('Boba Fett')
grafo.insertar_vertice('C_3PO')
grafo.insertar_vertice('Leia')
grafo.insertar_vertice('Rey')
grafo.insertar_vertice('Kylo Ren')
grafo.insertar_vertice('Chewbacca')
grafo.insertar_vertice('Han Solo')
grafo.insertar_vertice('R2_D2')
grafo.insertar_vertice('Obi_Wan kenobi') 
grafo.insertar_vertice('BB_8')

grafo.insertar_arista('Yoda', 'Darth Vader', 5)
grafo.insertar_arista('Yoda', 'Luke Skywalker', 4)
grafo.insertar_arista('Yoda', 'Boba Fett', 6)
grafo.insertar_arista('Yoda', 'Han Solo', 1)
grafo.insertar_arista('Yoda', 'Obi_Wan kenobi', 5)
grafo.insertar_arista('BB_8', 'Obi_Wan kenobi', 1)
grafo.insertar_arista('Han Solo', 'Darth Vader', 3)
grafo.insertar_arista('Chewbacca', 'Kylo Ren', 4)
grafo.insertar_arista('Kylo Ren', 'BB_8', 5)
grafo.insertar_arista('Chewbacca', 'Han Solo', 2)
grafo.insertar_arista('Chewbacca', 'C_3PO', 7)
grafo.insertar_arista('C_3PO', 'Leia', 3)
grafo.insertar_arista('Leia', 'Rey', 1)
grafo.insertar_arista('BB_8', 'R2_D2', 2)
grafo.insertar_arista('BB_8', 'Yoda', 4)
grafo.insertar_arista('Leia', 'R2_D2', 2)
grafo.insertar_arista('Leia', 'Chewbacca', 7)
grafo.insertar_arista('Leia', 'Kylo Ren', 2)

print('punto b')
print("Árbol de expanción mínima ")
arbol_minimo = grafo.kruskal()
print(arbol_minimo)
arbol_minimo = arbol_minimo[0].split('-')
peso_total = 0
for nodo in arbol_minimo:
    nodo = nodo.split(';')
    peso_total += int(nodo[2])
    print(f'{nodo[0]}-{nodo[1]}-{nodo[2]}')

print()
print('punto c')
grafo.barrido_lista_lista_2()
print()
print('punto e')
print(grafo.barrido_lista_lista_cant())